<%@ Page Title="" Language="vb" AutoEventWireup="false" MasterPageFile="~/Admin/admin.master" CodeBehind="admin_countries.aspx.vb" Inherits="Travel.Web.admin_countries" ValidateRequest="false" %>
<%@ Register Src="~/Admin/Shared/admin_addnewbuttons.ascx" TagPrefix="uc1" TagName="admin_addnewbuttons" %>

<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
    <script src="<%: ResolveUrl("~/Content/tinymce/tinymce.min.js")%>"></script>
    
    <script type="text/javascript">
        $(document).ready(function () {
            loadTinyMCE('<%: ResolveUrl("~/Content/bootstrap.min.css")%>', '<%: ResolveUrl("~/Content/blog.css")%>');
         });
    </script>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">

  <uc1:admin_addnewbuttons runat="server" id="btnAddNewButtons" />

    <%-- Details Form--%>

    <div id="divDetails" runat="server">
        <div class="panel-heading">
            <h3 class="panel-title">
                <asp:Label ID="lblDetailsFormTitle" Text="Add New Destination" runat="server" />
            </h3>
        </div>
        <div class="panel-body">
            <div class="form-group">
                <asp:Label ID="lblTitle" AssociatedControlID="txtCountry" runat="server" Text="Country:" />
                <asp:TextBox ID="txtCountry" runat="server" class="form-control" placeholder="Country" />
            </div>
            <div class="form-group">
                <asp:Label ID="lblContinent" AssociatedControlID="ddlContinent" runat="server" Text="Continent:" />
                <asp:DropDownList ID="ddlContinent" runat="server" CssClass="form-control" />
            </div>
              <div class="form-group">
                  <asp:Label ID="lblSeoTitle" AssociatedControlID="txtSeoTitle" runat="server" Text="SEO Title:" />
                  <asp:TextBox ID="txtSeoTitle" runat="server" CssClass="form-control" AutoCompleteType="None" MaxLength="64" />  
                 <asp:RequiredFieldValidator ID="valSEOTitle" ControlToValidate="txtSeoTitle" ValidationGroup="Country" runat="server" Text="SEO Title Required" ForeColor="Red" />
            </div>          
            <div class="form-group">
                  <asp:Label ID="lblSeoDescription" AssociatedControlID="txtSeoDescription" runat="server" Text="SEO Description:" />
                  <asp:TextBox ID="txtSeoDescription" runat="server" CssClass="form-control" AutoCompleteType="None" MaxLength="160" />
            </div>

            <div class="form-group">
                <asp:Label ID="lblBlog" AssociatedControlID="txtContent" runat="server" Text="Destination Page Content:" />
                <asp:TextBox ID="txtContent" runat="server" Rows="15" CssClass="form-control" TextMode="MultiLine" AutoCompleteType="None" />
            </div>

            <asp:UpdatePanel ID="upImage" runat="server">
                <ContentTemplate>
                      <div class="form-group">
                <asp:Label ID="lblCountryImage" AssociatedControlID="txtCountryImage" runat="server" Text="Country Image:" />
                   To add an image first upload it in Image Management and enter the ID here, lazy but its quick to program.....
                <asp:TextBox ID="txtCountryImage" runat="server" CssClass="form-control" AutoCompleteType="None" MaxLength="160" />
 
                 <asp:Image ID="imgCountryImage" runat="server" Height="80" />
                 <asp:RequiredFieldValidator ID="RequiredFieldValidator1" ControlToValidate="txtCountryImage" ValidationGroup="Country" runat="server" Text="Required" ForeColor="Red" />

                 <asp:Button ID="btnCheckImageID" runat="server"  text="Test Image" CssClass="btn btn-primary" />
            </div>
                </ContentTemplate>
            </asp:UpdatePanel>
           

            <asp:RequiredFieldValidator ID="valCountry" ControlToValidate="txtCountry" ValidationGroup="Country" runat="server" Text="Content - Required" ForeColor="Red" />

            <br />
            <asp:Button ID="btnSubmit" runat="server" Text="Submit" class="btn btn-default" ValidationGroup="Country" />

        </div>
    </div>

    <%--End Details Form--%>


    <%--Select Edit Grid--%>
    <div id="divEditGrid" class="panel panel-primary" runat="server">
        <div class="panel-heading">
            <h3 class="panel-title">
                <asp:Label ID="lblSelectGridTitle" Text="Select Country To Edit" runat="server" />
            </h3>
        </div>
        <div class="panel-body">

            <div class="table-responsive">

                <asp:GridView runat="server" ID="grdCountries" AutoGenerateColumns="false" AutoGenerateSelectButton="true" AutoGenerateDeleteButton="true" class="table table-striped" AllowPaging="true" PageSize="20">
                    <Columns>
                        <asp:BoundField DataField="CountryID" Visible="false" />
                        <asp:BoundField DataField="CountryDescription" Visible="true" HeaderText="Country" />
                    </Columns>
                </asp:GridView>

                <br />
                <asp:Label ID="lblError" runat="server" ForeColor="Red" /></asp:Label>

            </div>

        </div>
    </div>

    <%-- End Edit Grid--%>
</asp:Content>
