<%@ Page Title="" Language="vb" AutoEventWireup="false" MasterPageFile="~/Admin/admin.master" CodeBehind="admin_locations.aspx.vb" Inherits="Travel.Web.admin_locations" %>

<%@ Register Src="~/Admin/Shared/admin_addnewbuttons.ascx" TagPrefix="uc1" TagName="admin_addnewbuttons" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">

    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
     <script src="../Scripts/googlegraphs.js"></script>
    <script type="text/javascript">

        $(document).ready(function () {
            loadLocationChart()
        });

    </script>

</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">

    <uc1:admin_addnewbuttons runat="server" ID="btnAddNewButtons" />

    <%-- Details Form--%>

    <div id="divDetails" runat="server">
        <div class="panel-heading">
            <h3 class="panel-title">
                <asp:Label ID="lblDetailsFormTitle" Text="Add New Location" runat="server" />
            </h3>
        </div>
        <div class="panel-body">
            Find the latitude and longitude at <a href="http://www.latlong.net/">Latlong.net</a>

            <br />

            <div class="form-group">
                <asp:Label ID="lblDate" AssociatedControlID="txtdate" runat="server" Text="Date:" />

                <act:CalendarExtender ID="CalExtender" TargetControlID="txtDate" runat="server" Format="dd/MM/yyyy" />
                <asp:TextBox ID="txtDate" runat="server" class="form-control" placeholder="Date"  />
                <asp:RequiredFieldValidator ID="reqDate" runat="server" ValidationGroup="Location" ControlToValidate="txtDate" ForeColor="Red" Text="Required" />
             </div>
            <div class="form-group">
                <asp:Label ID="lblLocation" AssociatedControlID="txtLocation" runat="server" Text="Location:" />
                <asp:TextBox ID="txtLocation" runat="server" class="form-control" placeholder="Location: Vanocuver: Canada" ValidationGroup="Location" MaxLength="1000" />
                 <asp:RequiredFieldValidator ID="reqLocation" runat="server" ValidationGroup="Location" ControlToValidate="txtLocation" ForeColor="Red" Text="Required"  />
            </div>
            <div class="form-group">
                <asp:Label ID="lblLatitude" AssociatedControlID="txtLatitude" runat="server" Text="Latitude:" />
                <asp:TextBox ID="txtLatitude" runat="server" class="form-control" placeholder="53.2669145" MaxLength="12" ValidationGroup="Location" />
                  <asp:RequiredFieldValidator ID="reqLatitude" runat="server" ValidationGroup="Location" ControlToValidate="txtLatitude" ForeColor="Red" Text="Required"  />
            </div>
            <div class="form-group">
                <asp:Label ID="lblongitude" AssociatedControlID="txtLongitude" runat="server" Text="Longitude:" />
                <asp:TextBox ID="txtLongitude" runat="server" CssClass="form-control" AutoCompleteType="None" placeholder="-2.7648203" MaxLength="12" ValidationGroup="Location" />
                   <asp:RequiredFieldValidator ID="reqLongitude" runat="server" ValidationGroup="Location" ControlToValidate="txtLongitude" ForeColor="Red" Text="Required"   />
            </div>

            <br />
            <asp:Button ID="btnSubmit" runat="server" Text="Submit" class="btn btn-default" ValidationGroup="Location" />

        </div>
    </div>

    <%--End Details Form--%>


    <%--Select Edit Grid--%>
    <div id="divEditGrid" class="panel panel-primary" runat="server">
        <div class="panel-heading">
            <h3 class="panel-title">
                <asp:Label ID="lblSelectGridTitle" Text="Locations" runat="server" />
            </h3>
        </div>
        <div class="panel-body">

            <div class="table-responsive">

                <asp:GridView runat="server" ID="grdLocations" AutoGenerateColumns="false" AutoGenerateSelectButton="true" AutoGenerateDeleteButton="true" class="table table-striped" AllowPaging="true" PageSize="20">
                    <Columns>
                        <asp:BoundField DataField="LocationID" Visible="false" />
                        <asp:BoundField DataField="Date" Visible="true" HeaderText="Date" />
                        <asp:BoundField DataField="Location1" Visible="true" HeaderText="Location" />
                        <asp:BoundField DataField="latitude" Visible="true" HeaderText="Latitiude" />
                        <asp:BoundField DataField="longitude" Visible="true" HeaderText="Longitude" />
                    </Columns>
                </asp:GridView>

                <br />
                <asp:Label ID="lblError" runat="server" ForeColor="Red" />

            </div>

        </div>
    </div>

    <%-- End Edit Grid--%>

    <br />

      
      <div id="map_div" style="width: 100%; height: 600px"></div>
</asp:Content>
