'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class admin

    '''<summary>
    '''HeadContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HeadContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''mnuOverview1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuOverview1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mnuBlog1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuBlog1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mnuImages1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuImages1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mnuHomePage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuHomePage1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mnuCategorie1s control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuCategorie1s As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mnuCountries1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuCountries1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mnuLocations1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuLocations1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mnuErrorLog1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuErrorLog1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mnuOverview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuOverview As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mnuBlog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuBlog As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mnuImages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuImages As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mnuHomePage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuHomePage As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mnuCategories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuCategories As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mnuCountries control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuCountries As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mnuLocations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuLocations As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Li1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Li1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mnuWebsite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuWebsite As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblPageTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPageTitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''MainContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainContent As Global.System.Web.UI.WebControls.ContentPlaceHolder
End Class
