'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Blog
    Public Property BlogID As Integer
    Public Property Title As String
    Public Property DateCreated As Nullable(Of Date)
    Public Property Content As String
    Public Property AuthorID As Nullable(Of Integer)
    Public Property CountryID As Nullable(Of Integer)
    Public Property CategoryID As Nullable(Of Integer)
    Public Property [Date] As Nullable(Of Date)
    Public Property CategoryImageID As Nullable(Of Integer)
    Public Property IsVisible As Boolean
    Public Property IsFullScreen As Boolean
    Public Property ShowInSlideShow As Boolean
    Public Property SEOTitle As String
    Public Property SEODescription As String
    Public Property NiceDescription As String
    Public Property ShowPhotos As Boolean

    Public Overridable Property Author As Author
    Public Overridable Property Category As Category
    Public Overridable Property Country As Country

End Class
