'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Continent
    Public Property ContinentID As Integer
    Public Property ContinentDescription As String

    Public Overridable Property Countries As ICollection(Of Country) = New HashSet(Of Country)

End Class
