'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Country
    Public Property CountryID As Integer
    Public Property CountryDescription As String
    Public Property ContinentID As Nullable(Of Integer)
    Public Property CountryInformation As String
    Public Property SEOTitle As String
    Public Property SEODescription As String
    Public Property CountryImageID As Nullable(Of Integer)

    Public Overridable Property Blogs As ICollection(Of Blog) = New HashSet(Of Blog)
    Public Overridable Property Continent As Continent

End Class
