'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class UploadedImage
    Public Property ImageID As Integer
    Public Property ImageDescription As String
    Public Property ImageCaption As String
    Public Property BlogID As Nullable(Of Integer)
    Public Property DateUploaded As Date

End Class
