'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vCategory
    Public Property CategoryURL As String
    Public Property CategoryID As Integer
    Public Property CategoryDescription As String
    Public Property CategoryInformation As String
    Public Property ReverseDateOrder As Nullable(Of Boolean)
    Public Property IsFeature As Nullable(Of Boolean)
    Public Property ParentCategoryID As Nullable(Of Integer)
    Public Property ParentCountryID As Nullable(Of Integer)
    Public Property SEOTitle As String
    Public Property SEODescription As String
    Public Property ShowInMenu As Boolean
    Public Property CategoryImageID As Nullable(Of Integer)
    Public Property ImageDescription As String

End Class
