//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel.WebAPI.Providers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public int BlogID { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string Content { get; set; }
        public Nullable<int> AuthorID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> CategoryImageID { get; set; }
        public Nullable<bool> IsVisible { get; set; }
        public bool IsFullScreen { get; set; }
        public bool ShowInSlideShow { get; set; }
        public string SEOTitle { get; set; }
        public string SEODescription { get; set; }
        public string NiceDescription { get; set; }
        public bool ShowPhotos { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Category Category { get; set; }
        public virtual Country Country { get; set; }
    }
}
