//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel.WebAPI.Providers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Blogs = new HashSet<Blog>();
        }
    
        public int CategoryID { get; set; }
        public string CategoryDescription { get; set; }
        public string CategoryInformation { get; set; }
        public Nullable<bool> ReverseDateOrder { get; set; }
        public Nullable<bool> IsFeature { get; set; }
        public Nullable<int> ParentCategoryID { get; set; }
        public Nullable<int> ParentCountryID { get; set; }
        public string SEOTitle { get; set; }
        public string SEODescription { get; set; }
        public bool ShowInMenu { get; set; }
        public Nullable<int> CategoryImageID { get; set; }
    
        public virtual ICollection<Blog> Blogs { get; set; }
    }
}
