//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel.WebAPI.Providers
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebAPIContext : DbContext
    {
        public WebAPIContext()
            : base("name=WebAPIContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Author> Authors { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Continent> Continents { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<vBlog> vBlogs { get; set; }
        public virtual DbSet<vCategory> vCategories { get; set; }
        public virtual DbSet<vCountry> vCountries { get; set; }
        public virtual DbSet<vUploadedImage> vUploadedImages { get; set; }
        public virtual DbSet<Blog> Blogs { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<UploadedImage> UploadedImages { get; set; }
    }
}
