//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel.WebAPI.Providers
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadedImage
    {
        public int ImageID { get; set; }
        public string ImageDescription { get; set; }
        public string ImageCaption { get; set; }
        public Nullable<int> BlogID { get; set; }
        public System.DateTime DateUploaded { get; set; }
    }
}
