//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel.WebAPI.Providers
{
    using System;
    using System.Collections.Generic;
    
    public partial class vCountry
    {
        public string CountryURL { get; set; }
        public string ContinentDescription { get; set; }
        public int CountryID { get; set; }
        public string CountryDescription { get; set; }
        public Nullable<int> ContinentID { get; set; }
        public string CountryInformation { get; set; }
        public string SEOTitle { get; set; }
        public string SEODescription { get; set; }
        public Nullable<int> CountryImageID { get; set; }
        public string ImageDescription { get; set; }
    }
}
