'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class default_1

    '''<summary>
    '''litSearchText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litSearchText As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lnkViewAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkViewAll As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''plcCategorys control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plcCategorys As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''CategoryList1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CategoryList1 As Global.Travel.Web.CategoryList

    '''<summary>
    '''liPrev control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liPrev As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkPagePrev control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkPagePrev As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''plcPager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plcPager As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''liNext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liNext As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkPageNext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkPageNext As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnLoadMore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLoadMore As Global.System.Web.UI.WebControls.LinkButton
End Class
